### ISSUE TITLE
nil can't be coerced into Fixnum

### ISSUE THREAD

**Issue by menge101** [singram/cucumber_characteristics#6]
Following an unexpected exception in my test suite, I get the stack trace below.  I believe this is caused by the unhandled exception I received; I do not believe it is the cause.  But it illuminates that something isn't quite right with your monkey patch when an exception is thrown.

nil can't be coerced into Fixnum (TypeError)
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/cucumber_2x_step_patch.rb:46:in `+'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/cucumber_2x_step_patch.rb:46:in `block in scenario_profiles'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/cucumber_2x_step_patch.rb:39:in `each'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/cucumber_2x_step_patch.rb:39:in `scenario_profiles'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/profile_data.rb:41:in `feature_profiles'
(haml):120:in `block in render'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/haml-4.0.7/lib/haml/engine.rb:129:in `eval'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/haml-4.0.7/lib/haml/engine.rb:129:in `render'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/exporter.rb:27:in `to_html'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/exporter.rb:15:in `block in export'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/exporter.rb:15:in `open'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/exporter.rb:15:in `export'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber_characteristics-0.0.5/lib/cucumber_characteristics/formatter.rb:12:in `after_features'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:124:in `after'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:52:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/formatter/fanout.rb:15:in `each'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:40:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/quit.rb:17:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:19:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/compiler.rb:23:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:29:in `parse'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:18:in `compile'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:68:in `run!'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
/Users/nmenge/.rvm/gems/ruby-2.3.0/bin/cucumber:23:in `load'
/Users/nmenge/.rvm/gems/ruby-2.3.0/bin/cucumber:23:in `<main>'
/Users/nmenge/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/nmenge/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
[nmenge@pitm0715092c1(rodan_record_cleaning) ~/projects/mechagodzilla]$ mvim rerun.txt
[nmenge@pitm0715092c1(rodan_record_cleaning) ~/projects/mechagodzilla]$ 
[nmenge@pitm0715092c1(rodan_record_cleaning) ~/projects/mechagodzilla]$ 
[nmenge@pitm0715092c1(rodan_record_cleaning) ~/projects/mechagodzilla]$ TEST_ENV=local BROWSER=chrome rake cucumber:rerun
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:289: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/nmenge/.rvm/rubies/ruby-2.3.0/bin/ruby -S bundle exec cucumber  --profile rerun
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:289: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/nmenge/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:289: warning: Insecure world writable dir /usr/local in PATH, mode 040777

**Comment by singram** [comment]
Hmmm if you look in the feature files there is a step which raises and
exception.  Any thoughts on what the difference may be?

**Comment by menge101** [comment]
The exception was occurring in an around hook outside of the actual
cucumber feature step.  That may be what makes this situation unique.

**Comment by singram** [comment]
Ahhh yeah that would make a lot of sense since it's technically a exception
in the framework and not a step. Will take a look if I can some free time.
